install: 
	@echo "Installing..."
	@pip install -r requirements.txt
	@echo "Done."

#test:
#	@echo "Testing using pytest..."
#	@pytest src/test.py
#	@echo "Done."

run:
	@echo "Running..."
	@python task2/task2.py
	@echo "Done."